# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f1eea5b13380638623fa5b0f9b25aeb7b23059f3bec86aa597e40b4331224912d3d6809f7885cb8b7b06b4cd998e7ed4955ce178f102146fcc79e375f732bce

test:
  secret_key_base: 37c2bfc4f70e26d10a54ca7b084168d2b01199d59f9bd08d3b94b8ef7e49e823b06d537661a366057a1eba228038ebf73d6e703d78a4e01e443cdec679e3b5c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
